### ISSUE TITLE
Avoid use of .innerHTML

### ISSUE THREAD

**Issue by lucasschneider** [mi-g/weh#2]
Mozilla refuses to update my addon due to the usage of .innerHTML in the WEH background scripts due to security concerns. Is it possible to rewrite the scripts generated in the build to avoid using that function?

**Comment by rakotomandimby** [comment]
@lucasschneider , Why did you self close the issue?

**Comment by lucasschneider** [comment]
@rakotomandimby The use of .innerHTML is no longer a critical error, only a warning.
