### ISSUE TITLE
Who to finish the half ready converted videos

### ISSUE THREAD

**Issue by win10user123** [mi-g/weh#20]
Suddenly my Firefox has been crashed on Win 10 system during the converting.
Since the videos are now not available in the web how can I get the mp4 files if I see many vdh-14068WTDRUQXnHjLN.tmp files in the temp directory?

**Comment by mi-g** [comment]
For VDH related issues, please use the support forum: https://groups.google.com/g/video-downloadhelper-q-and-a/
This github project is dedicated to the companion app.
