### ISSUE TITLE
Installing npm modules

### ISSUE THREAD

**Issue by ivanminutillo** [mi-g/weh#4]
I am building a web extension using weh toolkit that should connect to a graphql layer to perform a login and fetch some info. I would like to use react-apollo module, but I dont see any package.json in the project folder...
Is it possible to install and use npm modules?

**Comment by mi-g** [comment]
You can add a `package.json` manifest to the main addon directory (where `src/`, `src-modules/`, `locales/`, ... are). The dependencies will be automatically resolved at build time.

For instance, the Video DownloadHelper `package.json` is:
```
{
  "name": "video-downloadhelper",
  "version": "7.1.2",
  "dependencies": {
    "deep-equal": "^1.0.1",
    "react-resize-detector": "^0.6.0",
    "react-transition-group": "^2.2.1",
    "reactstrap": "^5.0.0-alpha.3",
    "redux-watch": "^1.1.1"
  }
}
```
