### ISSUE TITLE
Trying to to get started

### ISSUE THREAD

**Issue by karfau** [mi-g/weh#5]
Hey there, 

I'm just getting started with building browser extensions, so please bare with me.
I would love to use typescript to do so, so I found your project,
and at first glance the Readme looks like you have put some thoughts and time into the project.
The dependencies don't look to outdated [on a first glance](https://github.com/mi-g/weh/network/dependencies).

I prefer installing libs locally, so I'm trying to find a different way of getting started:

In usual cases where people ask me to install something globally I'm nowadays using `npx` (usig the one that comes with node 8.9.4/npm 5.6.0 cofigured using nvm)
So I tried `npx weh init --prjdir test`
but (after npx taking "ages" to install it temporarily) it outputs the following:
`spawn gulp ENOENT`
and exits.

Since you suggest installing gulp globally (which I will not do), I'll try to consider `weh` as a devDependency.
running `npm i -D weh` provided the following output:
```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
> node-sass@4.7.2 install /home/karfau/dev/edit-in-page/node_modules/node-sass
> node scripts/install.js
Cached binary found at /home/karfau/.npm/node-sass/4.7.2/linux-x64-57_binding.node
> uglifyjs-webpack-plugin@0.4.6 postinstall /home/karfau/dev/edit-in-page/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js
> node-sass@4.7.2 postinstall /home/karfau/dev/edit-in-page/node_modules/node-sass
> node scripts/build.js
Binary found at /home/karfau/dev/edit-in-page/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
+ weh@2.0.0
added 1772 packages in 52.038s
```
So it looks like there are some deprecated libs in your dependency tree.
some are related to gulp-utils and just going to the page that is linked, it looks like it makes sense to get rid of it.
I don't know enough about gulp to be able to argue abut it, just asking,
**are there any plans of updating the dependencies?**

Ok, next step:  `./node_modules/.bin/weh init --prjdir .`
but oh, this looks familiar but with more details:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
What am I missing? I'm [attaching my `package-lock.json`](https://github.com/mi-g/weh/files/1777904/package-lock.json.zip) for you to be able to see what I got.
or is there just no way of not installing something globally?

**Comment by mi-g** [comment]
I don't have all the details in mind, but i remember i spent some time trying to use gulp from the local project. With the help of some forums, i concluded that this was not possible:  `gulp` has to be installed globally (in addition to being in the project dependencies) :/ From my point of view, this was not a big problem since `gulp` is a generic development tool, like `npm` or `nvm` and i do not mind too much having a machine-installed instance of this program.

You can try to prove me wrong (believe me, i'd like that !) but i'm afraid you are on your own here :)

**Comment by karfau** [comment]
Thx for the details.

Can you also say something about the other question i now highlighted in my post (the one about updating dependencies)?

I guess together those imformation my contribute to my decision wether I'm going to try to get this working...

**Comment by mi-g** [comment]
Yes, the `weh` dependencies are going to be updated very soon, like in a couple of days.
