### ISSUE TITLE
How do you translate choice options?

### ISSUE THREAD

**Issue by eric-bixby** [mi-g/weh#7]
In your skeleton code, you have "First Choice" defined in default-prefs.js.  While the README mentions you can define a translation in messages.json as "weh_prefs_label_<parameter name>_option_<parameter value>".  In the generated code, I see a reference to "weh_prefs_" + localeName + "\_option\_" + localeChoice", which doesn't have the "_label" in it.  Maybe that's just a typo in your README.

Anyway, could you please provide an example of how to provide a translation for "First Choice" in your skeleton code?

**Comment by eric-bixby** [comment]
I figured it out.  In default-prefs.js, rather than having a list of (name, value) pairs, just have a list of values.  Then messages.json does the mapping of value to the translated name.

**Comment by mi-g** [comment]
The `templates/inspector` code contains this example:
```
	...
	"weh_prefs_description_messages_display_mode": {
		"message": "How calls/replies should be displayed"
	},
	"weh_prefs_messages_display_mode_option_async": {
		"message": "Asynchronous"
	},
	"weh_prefs_messages_display_mode_option_sync_call": {
		"message": "Synchronous (on call)"
	},
	"weh_prefs_messages_display_mode_option_sync_reply": {
		"message": "Synchronous (on reply)"
	},
	...
```
