### ISSUE TITLE
error while creating new extension project in windows 10

### ISSUE THREAD

**Issue by p32929** [mi-g/weh#8]
![Screenshot (18)](https://user-images.githubusercontent.com/6418354/59287867-5de75180-8c94-11e9-8a25-3743b621b4f3.png)

**Comment by eric-bixby** [comment]
I see the same error when building (both Mac and Win10).  It was working when I last built around April.  Maybe a dependency is causing the problem.

**Comment by eric-bixby** [comment]
@p32929 
Here's my workaround:
1) Create an empty "package-lock.json" file.
2) Create a "package.json" file with just "{}"
This is not a fix, but you should at least be able to build your project again.

**Comment by mi-g** [comment]
closing
